### ISSUE TITLE
name clash with https://st.suckless.org/

### ISSUE THREAD

**Issue by glitsj16** [fabiensanglard/st#2]
Hi, great tool. I just read https://fabiensanglard.net/st/index.html and wanted to create a package for it in the [AUR](https://aur.archlinux.org/). Sadly enough there's already an app with the exact same binary name: https://st.suckless.org/ (packaged [here](https://aur.archlinux.org/packages/st)).

Just wanted to bring this to your attention. I could always package it as `ste` (space-time explorer) but that's bound to create confusion. I do realize these kind of clashes are always a downer after potential adrenaline heights from an initial 'aha-erlebnis' of coming up with a name in the first place. But that's out of my control :-).

**Comment by fabiensanglard** [comment]
Rename to ste,l send a pull request, and try again?

Fab

**Comment by fabiensanglard** [comment]
Rename tool to `ste` as of 8edc6f17de53fe46657c85ed60268d7f1ab138fb. If you want to attempt to AUR again, go for it!

**Comment by glitsj16** [comment]
@fabiensanglard

Very friendly to prepare for the name change! I'm preparing ste-git for the AUR and noticed that the Makefile needs one more `st` --> `ste` change:

https://github.com/fabiensanglard/st/blob/be51763e90f955d314aefcee7cb7af0248dbfedf/Makefile#L23

It's getting close to bedtime, so I'll hold off uploading ste-git to the AUR untill tomorrow. I could add a patch to fix this final issue, but the Makefile is broken now anyway...

Again, thanks for all your work, very much appreciated.

Regards

**Comment by denilsonsa** [comment]
People are fast. I was thinking about creating an AUR package, then I found the name clash, then I found this issue, where most stuff was already discussed. I'm late to the party by just one day. :)

Anyway, if the tool is being renamed to `ste`, I think the following next steps are needed, for consistency:

* [ ] This repository name should be renamed from [st](https://github.com/fabiensanglard/st) to [ste](https://github.com/fabiensanglard/ste).
* [ ] The blog article URL should also be renamed from [/st/](https://fabiensanglard.net/st/index.html) to [/ste/](https://fabiensanglard.net/ste/index.html)
* [ ] Any mentions of the old URL should be updated as well.
* [ ] The blog text should replace all occurrences of `st` to `ste`.
* [ ] The blog text could mention (maybe as a footnote) that the tool was originally named `st` but was renamed to `ste` quickly after being published, including a link to this issue.

**Comment by denilsonsa** [comment]
Hmm… Somehow `ste` is already in use by Fedora's RPM Sphere. However, it's an old package not updated in ten years, still using Qt 4 (we are already at Qt 6, and my system doesn't even come with Qt 4 libraries anymore), and the upstream website is gone (although the source is still available). We can probably ignore it, but I wanted to mention anyway.

* https://pkgs.org/download/ste
* https://github.com/rpmsphere/spec/blob/master/s/ste.spec
* https://web.archive.org/web/20120320162146/http://ste.sintegrial.com/pages/en/index.php
* https://github.com/sintegrial/ste

In case a second rename is wanted, looks like [stime](https://pkgs.org/download/stime) is available.

**Comment by fabiensanglard** [comment]
I am fine with renaming it to `stime`. However:

- Since it has been relinked, the URL of the article is now set in stone. I don't break links.
- For the same reason,  I don't want to rename the repo either.  If we update the `README.md`, it is enough.

**Comment by denilsonsa** [comment]
[GitHub automatically redirects traffic when a repository is renamed](https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository). Likewise, it would be possible to use a redirect on the article URL, but I understand it can be more difficult to setup depending on the hosting solution.
