### ISSUE TITLE
Extraneous EXEC Output

### ISSUE THREAD

**Issue by cwarden** [fabiensanglard/st#8]
I get a bunch of unexpected EXEC output if I run `st` with a long-running process, e.g. `st less -`.  Processes that are being spawned in other shells show up.  I also see processes spawned by the status bar for my window manager.

I'm not familiar with netlink.  How does `st` tell netlink what events it cares about (or filter out ones it doesn't care about)?

**Comment by fabiensanglard** [comment]
`st` monitors fork events [here](https://github.com/fabiensanglard/st/blob/main/code/src/netlink.cpp#L50).

If the process is a child of a currently tracked PID, it is added to the tracked set of PIDs.

I may not have understood properly the meaning of each field (it is not as straight forward as it sounds as explained [here](https://natanyellin.com/posts/understanding-netlink-process-connector-output/).

**Comment by fabiensanglard** [comment]
Turns out it was just a display issue. Fixed in be51763e90f955d314aefcee7cb7af0248dbfedf.
