### ISSUE TITLE
Print after ctrl-c

### ISSUE THREAD

**Issue by chapmanjacobd** [fabiensanglard/st#9]
Some commands run for an indeterminate amount of time. It would be nice to be able to still see the `ste` graph after signal interrupt `SIGINT`.

**Comment by fabiensanglard** [comment]
Commands can run for undermined amount of time but they eventually finish.

What usecase would this feature be useful for?

**Comment by chapmanjacobd** [comment]
it just seemed unexpected to not have an output. many analysis tools offer that functionality, especially when the result is aggregated or binned. For example, `ltrace -c`. One use-case would be servers. But I realize this tool does not provide much depth in terms of analysis so this feature is out of scope

**Comment by fabiensanglard** [comment]
This tool is opensource so you are free to add as much depth as you are capable of, both in terms of skills and fortitude.
